### PR TITLE
Avoid creating throw-away ResourceBuilders + fix namespace inferrer + inference caching.

### LINKED ISSUE #18: Serializable inferrer caching.

### PR DESCRIPTION
**Pull request by beauby**
Closes #18.

### CODE REVIEW

**Comment by richmolj** [comment]
Looks like there is a caching-related issue with this code. [This code](https://github.com/jsonapi-rb/jsonapi-serializable/blob/c852bed5232c8853d62c188d4c796f2fc22b5b6c/lib/jsonapi/serializable/resource_builder.rb#L44-L60) will cache based on class, independent of namespace. The result is an appropriately-namespaced `render` call will actually use the cached class instead. So if someone hits your `V1` API, then hits your `V2` API, you'll still use the `V1` resource.

**Comment by beauby** [comment]
Cache is not shared between render calls though?

**Comment by richmolj** [comment]
Sorry, you are correct. Honestly I saw the issue, I traced it back to this method, saw `@_cache`, then I commented before due diligence. The actual issue *is* within this method but *not* related to caching.

So, the actual issue seems related to Rails autoloading (or, class loading in general). This is unexpected behavior to me best illustrated with code. We get to [line 57](https://github.com/jsonapi-rb/jsonapi-serializable/blob/c852bed5232c8853d62c188d4c796f2fc22b5b6c/lib/jsonapi/serializable/resource_builder.rb#L57) and:

```ruby
defined?(SerializablePost) # => "constant", this class has loaded
defined?(V2::SerializablePost) # => nil, this class has not loaded

# Surprisingly, this will return SerializablePost - it won't error or load the correct constant
Object.const_get("V2::SerializablePost")
```

I have verified switching to `safe_constantize` fixes the issue, though that's Rails-specific :slightly_frowning_face:

**Comment by beauby** [comment]
Hmm I remember that kind of thing happening in AMS in the past – I'll look into it.

**Comment by richmolj** [comment]
@beauby any progress on this? I'm not running into issues because I'd like to bump versions of the related gems, but as this branch of serializable has hard dependencies I can't 😦

**Comment by beauby** [comment]
@richmolj Slowly getting back at it – I am still not sure how to prevent Rails' autoloading to go crazy in certain cases.

**Comment by richmolj** [comment]
@beauby I know this is not ideal but what about something with `if defined?(:safe_constantize)`? This could be moved to its own isolated private method/class that could be refactored later.

Alternatively, move this to an overrideable method, then override it in a railtie.

**Comment by beauby** [comment]
@richmolj I've been working on this. At this point I believe the least intrusive way of solving this is to monkey-patch `JSONAPI::Serializable::ResourceBuilder#reify_class` from within the `jsonapi-rails` railtie.

**Comment by richmolj** [comment]
Sounds about right :+1:

**Comment by beauby** [comment]
Closing this as it has been broken down into #62 #64 #63.

**Pull request closed without merging**
