### PR TITLE
Remove .to_json from renderer

### LINKED ISSUE #55: There should be a public API that allows to render in a hash.
At the moment it seems render returns only a String since it uses to_json. There should be a as_json equivalent publicly accessible.

https://github.com/jsonapi-rb/jsonapi-serializable/blob/master/lib/jsonapi/serializable/renderer.rb#L22

### PR DESCRIPTION
**Pull request by vasilakisfil**
Renderer returns a hash instead, fixes #55

### CODE REVIEW

**Comment by beauby** [comment]
@vasilakisfil Quick update: the reason I'm holding off merging this is simply that it's a breaking API change (though it should only impact people who use jsonapi-rb as a standalone ruby lib), and there are a few non-breaking changes that I'd like to release before `0.2`.

**Comment by vasilakisfil** [comment]
@beauby makes sense to me :+1:

**Comment by Aryk** [comment]
just curious, when do you think this will make it into repo? Perhaps in the meantime, we can do

`render_hash.to_json`

That way you won't break the api, but people can access the hash directly?

**Comment by beauby** [comment]
@Aryk Sorry for the late reply – this should make it in tomorrow.

**Comment by beauby** [comment]
@vasilakisfil Would you mind rebasing?

**Comment by beauby** [comment]
Hi @vasilakisfil – would you mind fixing the new test that's broken by this PR? (Basically remove the `JSON.parse()` call in `./spec/renderer/namespace_spec.rb:13`.

**Comment by vasilakisfil** [comment]
Sure, I can do it later today!

**Comment by vasilakisfil** [comment]
@beauby fixed!

**Comment by beauby** [comment]
@vasilakisfil Finally merging – thanks!

**Pull request merged**
